version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 5173:5173
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3456:3456
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/projects

  db:
    image: mongo:5.0.7
    container_name: database
    platform: linux/x86_64
    ports:
      - 27017:27017
    restart: 'always'

networks:
  default:
    name: portfolio