version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 5173:5173
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3456:3456
    platform: linux/x86_64
    working_dir: /app-backend

networks:
  default:
    name: portfolio